Refactor extraction pipeline.2
swisstopo/swissgeol-boreholes-dataextraction pull request #23
Opened 2024-04-03 12:19 UTC by redur

Here the discussed proposition.

I think we can extend the thought even further and include the draw_predictions earlier. That would require that we load the ground truth earlier as well. I keep this for the future as the current implementation currently already serves for discussion.

2024-04-03 12:22 UTC, redur commented on src/stratigraphy/main.py
> +                            draw_lines_on_pdfs(filename, page, geometric_lines)
maybe rename to: `draw_lines_on_page`

2024-04-03 12:23 UTC, redur commented on src/stratigraphy/line_detection.py
> +    Note: now the function draw_lines_on_pdfs may not even be needed any more.
Not sure it's worth having a separate function that essentially only has two lines of code. The MLFLow warning can be thrown somewhere else as well.

2024-04-03 12:39 UTC, redur commented
Now single files work as well without the temporary directory.

2024-04-05 08:15 UTC, stijnvermeeren-swisstopo requested changes

2024-04-05 08:33 UTC, redur commented
Thank you. Comments are addressed.

2024-04-05 09:37 UTC, stijnvermeeren-swisstopo approved these changes

2024-04-05 09:38 UTC, merged