Close LGVISIUM-52: Remove grouping by page
swisstopo/swissgeol-boreholes-dataextraction pull request #70
Opened 2024-07-31 10:07 UTC by dcleres

Remove the page based logic in the code. The `prediction.json`  has now the following shape: 

```json
{
    "685256002-bp.pdf": {
        "language": "de",
        "metadata": {
            "coordinates": null
        },
        "layers": [
            {
                "material_description": {
                    "text": "grauersiltigsandigerkiesauffullung",
                    "rect": [
                        232.78799438476562,
                        130.18496704101562,
                        525.6640014648438,
                        153.54295349121094
                    ],
                    "lines": [
                        {
                            "text": "grauer, siltig-sandiger Kies (Auffullung)",
                            "rect": [
                                232.78799438476562,
                                130.18496704101562,
                                525.6640014648438,
                                153.54295349121094
                            ],
                            "page": 1
                        }
                    ],
                    "page": 1
                },
                "depth_interval": {
                    "start": null,
                    "end": {
                        "value": 0.4,
                        "rect": [
                            125.25399780273438,
                            140.2349853515625,
                            146.10398864746094,
                            160.84498596191406
                        ],
                        "page": 1
                    }
                }
            },
...
            {
                "material_description": {
                    "text": "dunkelgrauermagererztsandigerlehm",
                    "rect": [
                        246.42300415039062,
                        708.9439697265625,
                        438.72283935546875,
                        722.6839599609375
                    ],
                    "lines": [
                        {
                            "text": "dunkelgrauer, magerer, z.T. sandiger Lehm",
                            "rect": [
                                246.42300415039062,
                                708.9439697265625,
                                438.72283935546875,
                                722.6839599609375
                            ],
                            "page": 1
                        }
                    ],
                    "page": 1
                },
                "depth_interval": {
                    "start": {
                        "value": 9.9,
                        "rect": [
                            163.56900024414062,
                            684.2750244140625,
                            177.468994140625,
                            698.0150146484375
                        ],
                        "page": 1
                    },
                    "end": {
                        "value": 12.0,
                        "rect": [
                            160.0050048828125,
                            745.1210327148438,
                            177.5189971923828,
                            757.4869995117188
                        ],
                        "page": 1
                    }
                }
            }
        ],
        "depths_materials_column_pairs": [
            {
                "depth_column": {
                    "rect": [
                        160.0050048828125,
                        410.78302001953125,
                        178.76199340820312,
                        757.4869995117188
                    ],
                    "entries": [
                        {
                            "value": 0.2,
                            "rect": [
                                163.0070037841797,
                                410.78302001953125,
                                176.90699768066406,
                                424.52301025390625
                            ],
                            "page": 1
                        },
                        {
                            "value": 2.9,
                            "rect": [
                                162.36900329589844,
                                485.98602294921875,
                                176.2689971923828,
                                499.72601318359375
                            ],
                            "page": 1
                        },
                        {
                            "value": 3.1,
                            "rect": [
                                163.23500061035156,
                                495.28399658203125,
                                177.13499450683594,
                                509.02398681640625
                            ],
                            "page": 1
                        },
                        {
                            "value": 3.7,
                            "rect": [
                                163.31199645996094,
                                509.58197021484375,
                                177.2119903564453,
                                523.3219604492188
                            ],
                            "page": 1
                        },
                        {
                            "value": 4.0,
                            "rect": [
                                163.27000427246094,
                                517.2839965820312,
                                177.1699981689453,
                                531.0239868164062
                            ],
                            "page": 1
                        },
                        {
                            "value": 4.3,
                            "rect": [
                                163.1320037841797,
                                526.6389770507812,
                                177.03199768066406,
                                540.3789672851562
                            ],
                            "page": 1
                        },
                        {
                            "value": 5.1,
                            "rect": [
                                163.4720001220703,
                                548.4299926757812,
                                178.76199340820312,
                                563.5440063476562
                            ],
                            "page": 1
                        },
                        {
                            "value": 5.7,
                            "rect": [
                                163.5570068359375,
                                567.0780029296875,
                                177.45700073242188,
                                580.8179931640625
                            ],
                            "page": 1
                        },
                        {
                            "value": 7.0,
                            "rect": [
                                163.42300415039062,
                                602.1010131835938,
                                177.322998046875,
                                615.8410034179688
                            ],
                            "page": 1
                        },
                        {
                            "value": 7.7,
                            "rect": [
                                163.625,
                                622.0120239257812,
                                177.52499389648438,
                                635.7520141601562
                            ],
                            "page": 1
                        },
                        {
                            "value": 8.6,
                            "rect": [
                                163.5500030517578,
                                647.9769897460938,
                                177.4499969 [...]

2024-08-06 10:56 UTC, stijnvermeeren-swisstopo requested changes
I pushed two commits:
- one fixing 2 TODOs in predictions.py (many thanks for highlighting those!) 
- one addressing the last point in the JIRA ticket:
  - _While we are at it, can we remove the postprocessing (lowercase, removing whitespace) from the "text" field of the material description (e.g. "text": "kiesmitvielsandwenigsiltundtonbraungrau")? It would make more sense to me if this postprocessing is only done for the purposes of evaluation / comparing with ground truth, but the predictions.json file should actually contain the original text from the document without postprocessing (as is already the case for the individual lines)._

Remaining points from the ticket:
- _Importing the extracted data in Label Studio still works_
  - Did you check this @dcleres ?
- _README documentation is updated_
  - The README currently contains a JSON example with the old structure

I'm not a big fan of the fact that we had to add `page_number=1` in so many unit tests that are not really concerned with page number logic at all. However, I don't really see an immediate solution to this. Unless you see an easy way to avoid this, I'm happy to accept it like this.

The other change requests that I've added are all pretty minor, I think.

2024-08-15 09:31 UTC, dcleres commented on src/stratigraphy/util/coordinate_extraction.py
>              page_number = page.number + 1  # page.number is 0-based
Good catch. thank you. I do not know how I missed that.

2024-08-15 09:36 UTC, dcleres commented on src/stratigraphy/main.py
> +                    assert len(page_heights_list) == len(page_widths_list) == doc.page_count, "Page count mismatch."
I am fine with that.

2024-08-15 09:46 UTC, dcleres commented on src/stratigraphy/util/find_depth_columns.py
> +                layer_depth_column_entry = extract_layer_depth_interval(input_string, word.rect, page_number)
Thank you I missed the fact that the word knows its page.

2024-08-15 11:30 UTC, dcleres commented on src/stratigraphy/util/predictions.py
> +        self.layers: list[LayerPrediction] = sorted(layers, key=lambda layer: layer.material_description.rect.y0)
I think during development, it helped me to better find the text on the page and make a few visual tests. However, you are correct that this does not impact the performance of the extraction. So, I will get back to the original version. Thank you for highlighting this.

2024-08-15 11:42 UTC, dcleres commented
I found during the review that the file: `src/scripts/label_studio_annotation_to_ground_truth.py` also needs to be adapted to match the new format. I will start working on this.

2024-08-15 11:46 UTC, dcleres commented
Thank you for your comment regarding the PR. I resolved all the issues you highlighted which are relevant to this part of the code. The changes required to the label studio repository will be merged into the respective repository. 

> I'm not a big fan of the fact that we had to add page_number=1 in so many unit tests that are not really concerned with page number logic at all. However, I don't see an immediate solution to this. Unless you see an easy way to avoid this, I'm happy to accept it as is.

Regarding this comment, I fully agree with you, but I also have not found a fundamentally better way to solve this issue. I edited the tests and added a constant called `PAGE_NUMBER` that mitigates this issue to some extent. 

While doing this, I also realized that we are not doing any tests on files that have more than one page. Should a test be added for this as well?

2024-08-20 13:23 UTC, stijnvermeeren-swisstopo commented
> While doing this, I also realized that we are not performing any tests on files with more than one page. @stijnvermeeren-swisstopo, should a test be added for this as well?

That would certainly be useful as well, but it's not a top priority. If you want to work on that, I would certainly do it in a separate PR, so that we can close this one already now.

2024-08-20 13:24 UTC, stijnvermeeren-swisstopo approved these changes
I pushed a minor simplification of the page dimensions code (https://github.com/swisstopo/swissgeol-boreholes-dataextraction/pull/70/commits/4404eff5b61c6827d054bc000e406aedb3f5ab32).

Everything looks good to me now.

2024-08-20 13:49 UTC, merged