Close #LGVISIUM-57: Downgraded the PyMuPDF version and updated the README
swisstopo/swissgeol-boreholes-dataextraction pull request #73
Opened 2024-08-22 10:53 UTC by dcleres

Some of our PDF documents have performance issues with newer versions of PyMuPDF. This change in the code makes it possible to use an older version of the library, which does not present these performance issues.

2024-08-22 15:22 UTC, dcleres commented
<img width="959" alt="Screenshot 2024-08-22 at 17 07 44" src="https://github.com/user-attachments/assets/5b398878-d132-44e7-8791-3269d3cfb458">

When using the 1.24.1 version of the code, the change of speed between drawing on the Page or on the Shape (new version) is not large. See 2.5 min to 2.4 min. However, this makes the code compatible with the more recent versions of the PyMuPDF and was the way suggested by one of the developers. (See https://github.com/pymupdf/PyMuPDF/issues/3800)

I added the functionality to log the runtime per document. @stijnvermeeren-swisstopo if you think that it is not necessary we can remove it. However, I do believe that every time we will try to improve the performance we will have to rewrite this code.

2024-08-26 10:02 UTC, stijnvermeeren-swisstopo requested changes
Thanks a lot for reaching out to the PyMuPDF devs and for identifying the cause of the performance change!

I managed to further improve the performance by reducing the number of shape.commit() calls. First of all, the one in draw_layer was redundant anyway. Then I managed to unify the remaining five calls per page to a single one.

With this, I would also be happy to upgrade again to the latest version of PyMuPDF, as the performance advantages of the old version no longer seem to outweigh the benefits of being able to use the latest and greatest library version ;).

I also refactored the creation of the "timing" dataframes to work with a list of dicts instead of a dict of lists. For me, the new way is cleaner and slightly simpler.

2024-08-26 12:22 UTC, dcleres commented on src/stratigraphy/main.py
> +            mlflow.log_metric("total_runtime", round(total_runtime, 2))
Yes, this is true. I left it as I saw the value of tracking the processing time for each single file, which is currently not done by mlflow (correct me if I am wrong) as this is how you detected the drop in performance in the first place. I was thinking that at a later time, we could have a specific test that makes sure that no file takes longer than, let's say, 10 seconds to be annotated. But if this is not necessary, then I am happy to remove this artifact from the code.

2024-08-26 12:22 UTC, dcleres commented
> I managed to further improve the performance by reducing the number of shape.commit() calls. First of all, the one in draw_layer was redundant anyway. Then I managed to unify the remaining five calls per page to a single one.

That is great! 

I will clean up the code and make push the new changes this afternoon.

2024-08-26 12:24 UTC, dcleres commented on src/stratigraphy/main.py
> +            mlflow.log_metric("total_runtime", round(total_runtime, 2))
@stijnvermeeren-swisstopo let me know what you think.

2024-08-26 13:05 UTC, dcleres commented
![Screenshot 2024-08-26 at 15 03 29](https://github.com/user-attachments/assets/90b0bbb4-cb37-4d3c-aaab-88a0014a043b)

I tried the code with the latest changes (on top), and we are pretty much on par with the performance we had with the older version (on the bottom). Super cool!

2024-08-26 13:11 UTC, dcleres commented on src/stratigraphy/main.py
> +            mlflow.log_metric("total_runtime", round(total_runtime, 2))
Ah okay. Then I will remove it.

2024-08-26 13:16 UTC, dcleres commented
@stijnvermeeren-swisstopo the code should not log single file timing information anymore. Are we good to merge?

2024-08-26 13:49 UTC, merged