Close #LGVISIUM-85: Added possibility to pass the AWS Credentials in an .env file or as environment variables
swisstopo/swissgeol-boreholes-dataextraction pull request #89
Opened 2024-10-02 10:07 UTC by dcleres

I implemented the changes required by test users to make it possible to use environment variables to specify the AWS credentials to the API. The credentials can also be specified in an `.env` file now. 

The `create_pngs` path also now directly returns the file path within the S3 bucket without specifying the bucket URL.

2024-10-07 11:16 UTC, dcleres commented on tests/test_data_extraction_from_bbox.py
> +    s3_client.list_buckets()
It was a test for me to see more readily if the mocking of the S3 bucket worked. You are right; it is not needed anymore.

2024-10-07 11:31 UTC, dcleres commented on tests/test_create_pngs.py
>      for png_url in json_response["png_urls"]:
I opened a Ticket on Jira for this.

2024-10-07 11:32 UTC, dcleres commented on README.md
> +    To run the docker image from `Dockerfile` locally:
Good catch thank you!

2024-10-07 11:38 UTC, dcleres commented
@stijnvermeeren-swisstopo thank you very much for your review. I addressed your comment and replied to the questions. Regarding the naming of the field that contains the naming and locations of the created PNG files after calling the API, I opened a ticket for that on Jira, as we need to sync with Geowerkstatt.

2024-10-07 13:31 UTC, stijnvermeeren-swisstopo requested changes
I don't see the requested changes in the README.md yet, did you by any change forget to push them?

2024-10-07 13:31 UTC, stijnvermeeren-swisstopo commented on src/app/common/aws.py
> +        filename (str): The filename of the PDF image.
```suggestion
        filename (str): The filename of the document.
```

2024-10-07 14:07 UTC, dcleres commented
@stijnvermeeren-swisstopo Yes, indeed, the README was not included in my commit. I also addressed the comment you made. Thank you for your patience.

2024-10-08 07:36 UTC, stijnvermeeren-swisstopo approved these changes
LGTM!

2024-10-08 08:26 UTC, merged