Close LGVISIUM-77: Wrong elevation value selected within bounding box
swisstopo/swissgeol-boreholes-dataextraction pull request #91
Opened 2024-10-03 08:00 UTC by dcleres

Started to sort vertically the different text lines matched around the matched keyword. By sorting, it was possible to test which was the closest to the keyword first and thus reduce the number of false positives or errors in elevation and groundwater detection. 

@stijnvermeeren-swisstopo In today's stand-up, we discussed the possibility of vertically and horizontally sorting the text. Currently, all the issues I found are solved with this code in combination with the improvements you made in the OCR processing. However, if you wish, I can also try this technique. 

<img width="1101" alt="Screenshot 2024-10-03 at 09 30 24" src="https://github.com/user-attachments/assets/a7fe327d-04b5-4c55-bdf2-b6019a7a7744">

The metrics from the `main` branch are in silent-quail-641, and the performance of this branch is `ambitious-mule-939`

2024-10-08 07:30 UTC, stijnvermeeren-swisstopo requested changes
Could you add a comment to https://jira.swisstopo.ch/browse/LGVISIUM-77 to describe the decision to only sort by vertical distance, as this already improves the results sufficiently, and that we therefore did not yet test the idea of looking horizontally and vertically (but not diagonally) from the key line.

2024-10-08 07:30 UTC, stijnvermeeren-swisstopo commented on src/stratigraphy/data_extractor/data_extractor.py
> +        # Sort by distance from key_line
```suggestion
        # Sort by vertical distance between the top of the feature line and the top of key_line
```

2024-10-09 13:27 UTC, dcleres commented
@stijnvermeeren-swisstopo I added a description on the rational of only sorting vertically to Jira and how this could be improved.

2024-10-10 08:54 UTC, stijnvermeeren-swisstopo approved these changes
Thanks for adding the comment on the Jira ticket. LGTM!

2024-10-10 10:13 UTC, merged